/**
 * Writes public/robots.txt and public/sitemap.xml from a single source of
 * truth, so the deployed domain never has to be edited in three places.
 *
 * Set SITE_URL in the environment (the GitHub Actions workflow does this
 * automatically from the Pages URL). Runs as `prebuild`.
 */
import { writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const OUT = resolve(dirname(fileURLToPath(import.meta.url)), '..', 'public')

// Trailing slash normalised so we never emit a double slash.
const SITE_URL = (process.env.SITE_URL || 'https://ruby9264.github.io').replace(/\/+$/, '')

writeFileSync(
  resolve(OUT, 'robots.txt'),
  `User-agent: *\nAllow: /\n\nSitemap: ${SITE_URL}/sitemap.xml\n`,
)

writeFileSync(
  resolve(OUT, 'sitemap.xml'),
  `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by scripts/generate-seo.mjs. Edit SITE_URL, not this file. -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <url>
    <loc>${SITE_URL}/</loc>
    <changefreq>monthly</changefreq>
    <priority>1.0</priority>
  </url>
</urlset>
`,
)

console.log(`SEO files written for ${SITE_URL}`)
